# Render service configuration (backend)
services:
  - type: web
    name: guitarbuddy-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm run start
    repo: Hrudai-Nirmal/GuitarBud
    branch: main
    root: backend
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        sync: false
